// SPDX-License-Identifier: MIT
//
// TJS2 VM opcode enumeration (0..=127).
//
// This enum and its mapping is used by the structured disassembler that operates on Object.code
// (little-endian i16 word stream).
//
// Note: Different Kirikiri builds may have different opcode id ordering. If you observe mismatches,
// adjust `from_u16` accordingly.

use anyhow::{bail, Result};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    Nop,
    Const,
    Cp,
    Cl,
    Ccl,
    Tt,
    Tf,
    Ceq,
    Cdeq,
    Clt,
    Cgt,
    Setf,
    Setnf,
    Lnot,
    Nf,
    Jf,
    Jnf,
    Jmp,
    Inc,
    Incpd,
    Incpi,
    Incp,
    Dec,
    Decpd,
    Decpi,
    Decp,
    Lor,
    Lorpd,
    Lorpi,
    Lorp,
    Land,
    Landpd,
    Landpi,
    Landp,
    Bor,
    Borpd,
    Borpi,
    Borp,
    Bxor,
    Bxorpd,
    Bxorpi,
    Bxorp,
    Band,
    Bandpd,
    Bandpi,
    Bandp,
    Sar,
    Sarpd,
    Sarpi,
    Sarp,
    Sal,
    Salpd,
    Salpi,
    Salp,
    Sr,
    Srpd,
    Srpi,
    Srp,
    Add,
    Addpd,
    Addpi,
    Addp,
    Sub,
    Subpd,
    Subpi,
    Subp,
    Mod,
    Modpd,
    Modpi,
    Modp,
    Div,
    Divpd,
    Divpi,
    Divp,
    Idiv,
    Idivpd,
    Idivpi,
    Idivp,
    Mul,
    Mulpd,
    Mulpi,
    Mulp,
    Bnot,
    Asc,
    Chr,
    Num,
    Chs,
    Inv,
    Chkinv,
    Int,
    Real,
    Str,
    Octet,
    Typeof,
    Typeofd,
    Typeofi,
    Eval,
    Eexp,
    Chkins,
    Call,
    Calld,
    Calli,
    New,
    Gpd,
    Gpds,
    Gpi,
    Gpis,
    Spd,
    Spde,
    Spdeh,
    Spds,
    Spi,
    Spie,
    Spis,
    Getp,
    Setp,
    Deld,
    Deli,
    Srv,
    Ret,
    Entry,
    Extry,
    Throw,
    Chgthis,
    Global,
    Addci,
    Regmember,
    Debugger,
}

impl Opcode {
    pub fn from_u16(v: u16) -> Result<Self> {
        use Opcode::*;
        Ok(match v {
            0 => Nop,
            1 => Const,
            2 => Cp,
            3 => Cl,
            4 => Ccl,
            5 => Tt,
            6 => Tf,
            7 => Ceq,
            8 => Cdeq,
            9 => Clt,
            10 => Cgt,
            11 => Setf,
            12 => Setnf,
            13 => Lnot,
            14 => Nf,
            15 => Jf,
            16 => Jnf,
            17 => Jmp,
            18 => Inc,
            19 => Incpd,
            20 => Incpi,
            21 => Incp,
            22 => Dec,
            23 => Decpd,
            24 => Decpi,
            25 => Decp,
            26 => Lor,
            27 => Lorpd,
            28 => Lorpi,
            29 => Lorp,
            30 => Land,
            31 => Landpd,
            32 => Landpi,
            33 => Landp,
            34 => Bor,
            35 => Borpd,
            36 => Borpi,
            37 => Borp,
            38 => Bxor,
            39 => Bxorpd,
            40 => Bxorpi,
            41 => Bxorp,
            42 => Band,
            43 => Bandpd,
            44 => Bandpi,
            45 => Bandp,
            46 => Sar,
            47 => Sarpd,
            48 => Sarpi,
            49 => Sarp,
            50 => Sal,
            51 => Salpd,
            52 => Salpi,
            53 => Salp,
            54 => Sr,
            55 => Srpd,
            56 => Srpi,
            57 => Srp,
            58 => Add,
            59 => Addpd,
            60 => Addpi,
            61 => Addp,
            62 => Sub,
            63 => Subpd,
            64 => Subpi,
            65 => Subp,
            66 => Mod,
            67 => Modpd,
            68 => Modpi,
            69 => Modp,
            70 => Div,
            71 => Divpd,
            72 => Divpi,
            73 => Divp,
            74 => Idiv,
            75 => Idivpd,
            76 => Idivpi,
            77 => Idivp,
            78 => Mul,
            79 => Mulpd,
            80 => Mulpi,
            81 => Mulp,
            82 => Bnot,
            83 => Asc,
            84 => Chr,
            85 => Num,
            86 => Chs,
            87 => Inv,
            88 => Chkinv,
            89 => Int,
            90 => Real,
            91 => Str,
            92 => Octet,
            93 => Typeof,
            94 => Typeofd,
            95 => Typeofi,
            96 => Eval,
            97 => Eexp,
            98 => Chkins,
            99 => Call,
            100 => Calld,
            101 => Calli,
            102 => New,
            103 => Gpd,
            104 => Gpds,
            105 => Gpi,
            106 => Gpis,
            107 => Spd,
            108 => Spde,
            109 => Spdeh,
            110 => Spds,
            111 => Spi,
            112 => Spie,
            113 => Spis,
            114 => Getp,
            115 => Setp,
            116 => Deld,
            117 => Deli,
            118 => Srv,
            119 => Ret,
            120 => Entry,
            121 => Extry,
            122 => Throw,
            123 => Chgthis,
            124 => Global,
            125 => Addci,
            126 => Regmember,
            127 => Debugger,
            _ => bail!("unknown opcode id {}", v),
        })
    }

    pub fn mnemonic(&self) -> &'static str {
        use Opcode::*;
        match self {
            Nop => "nop",
            Const => "const",
            Cp => "cp",
            Cl => "cl",
            Ccl => "ccl",
            Tt => "tt",
            Tf => "tf",
            Ceq => "ceq",
            Cdeq => "cdeq",
            Clt => "clt",
            Cgt => "cgt",
            Setf => "setf",
            Setnf => "setnf",
            Lnot => "lnot",
            Nf => "nf",
            Jf => "jf",
            Jnf => "jnf",
            Jmp => "jmp",
            Inc => "inc",
            Incpd => "incpd",
            Incpi => "incpi",
            Incp => "incp",
            Dec => "dec",
            Decpd => "decpd",
            Decpi => "decpi",
            Decp => "decp",
            Lor => "lor",
            Lorpd => "lorpd",
            Lorpi => "lorpi",
            Lorp => "lorp",
            Land => "land",
            Landpd => "landpd",
            Landpi => "landpi",
            Landp => "landp",
            Bor => "bor",
            Borpd => "borpd",
            Borpi => "borpi",
            Borp => "borp",
            Bxor => "bxor",
            Bxorpd => "bxorpd",
            Bxorpi => "bxorpi",
            Bxorp => "bxorp",
            Band => "band",
            Bandpd => "bandpd",
            Bandpi => "bandpi",
            Bandp => "bandp",
            Sar => "sar",
            Sarpd => "sarpd",
            Sarpi => "sarpi",
            Sarp => "sarp",
            Sal => "sal",
            Salpd => "salpd",
            Salpi => "salpi",
            Salp => "salp",
            Sr => "sr",
            Srpd => "srpd",
            Srpi => "srpi",
            Srp => "srp",
            Add => "add",
            Addpd => "addpd",
            Addpi => "addpi",
            Addp => "addp",
            Sub => "sub",
            Subpd => "subpd",
            Subpi => "subpi",
            Subp => "subp",
            Mod => "mod",
            Modpd => "modpd",
            Modpi => "modpi",
            Modp => "modp",
            Div => "div",
            Divpd => "divpd",
            Divpi => "divpi",
            Divp => "divp",
            Idiv => "idiv",
            Idivpd => "idivpd",
            Idivpi => "idivpi",
            Idivp => "idivp",
            Mul => "mul",
            Mulpd => "mulpd",
            Mulpi => "mulpi",
            Mulp => "mulp",
            Bnot => "bnot",
            Asc => "asc",
            Chr => "chr",
            Num => "num",
            Chs => "chs",
            Inv => "inv",
            Chkinv => "chkinv",
            Int => "int",
            Real => "real",
            Str => "string",
            Octet => "octet",
            Typeof => "typeof",
            Typeofd => "typeofd",
            Typeofi => "typeofi",
            Eval => "eval",
            Eexp => "eexp",
            Chkins => "chkins",
            Call => "call",
            Calld => "calld",
            Calli => "calli",
            New => "new",
            Gpd => "gpd",
            Gpds => "gpds",
            Gpi => "gpi",
            Gpis => "gpis",
            Spd => "spd",
            Spde => "spde",
            Spdeh => "spdeh",
            Spds => "spds",
            Spi => "spi",
            Spie => "spie",
            Spis => "spis",
            Getp => "getp",
            Setp => "setp",
            Deld => "deld",
            Deli => "deli",
            Srv => "srv",
            Ret => "ret",
            Entry => "entry",
            Extry => "extry",
            Throw => "throw",
            Chgthis => "chgthis",
            Global => "global",
            Addci => "addci",
            Regmember => "regmember",
            Debugger => "debugger",
        }
    }

    /// Number of operand words that follow the opcode word, if fixed.
    /// Variable-length call/new family returns None.
    pub fn fixed_operand_words(&self) -> Option<usize> {
        use Opcode::*;
        match self {
            // 0 operands
            Nop | Nf | Ret | Extry | Regmember | Debugger => Some(0),

            // 2 operands
            Const => Some(2),
            Cp => Some(2),
            Ccl => Some(2),
            Ceq | Cdeq | Clt | Cgt | Lor | Land | Bor | Bxor | Band | Sar | Sal | Sr | Add | Sub | Mod | Div | Idiv | Mul | Chgthis | Addci => Some(2),

            // 1 operand (register or jump target)
            Cl | Tt | Tf | Setf | Setnf | Lnot | Inc | Dec | Bnot | Asc | Chr | Num | Chs | Inv | Chkinv | Int | Real | Str | Octet | Typeof | Eval | Eexp | Srv | Throw | Global => Some(1),

            // jumps
            Jf | Jnf | Jmp => Some(1),
            Entry => Some(2),

            // member access
            Typeofd | Typeofi => Some(2),
            Chkins => Some(2),

            // unary member/property
            Incpd | Incpi | Decpd | Decpi => Some(3),
            Incp | Decp => Some(2),

            // binary member/property
            Lorpd | Lorpi | Landpd | Landpi | Borpd | Borpi | Bxorpd | Bxorpi | Bandpd | Bandpi
            | Sarpd | Sarpi | Salpd | Salpi | Srpd | Srpi | Addpd | Addpi | Subpd | Subpi | Modpd | Modpi | Divpd | Divpi
            | Idivpd | Idivpi | Mulpd | Mulpi => Some(4),

            Lorp | Landp | Borp | Bxorp | Bandp | Sarp | Salp | Srp | Addp | Subp | Modp | Divp | Idivp | Mulp => Some(3),

            // get/set member
            Gpd | Gpds | Gpi | Gpis => Some(3),
            Spd | Spde | Spdeh | Spds | Spi | Spie | Spis => Some(3),

            Getp | Setp => Some(2),
            Deld | Deli => Some(3),

            // variable length
            Call | Calld | Calli | New => None,
        }
    }
}
