// Auto-generated from krkrz tjsInterCodeGen.h (tTJSVMCodes).
#[allow(dead_code)]
pub mod vm {
    pub const VM_COUNT: usize = 128;
    pub const VM_NOP: i32 = 0;
    pub const VM_CONST: i32 = 1;
    pub const VM_CP: i32 = 2;
    pub const VM_CL: i32 = 3;
    pub const VM_CCL: i32 = 4;
    pub const VM_TT: i32 = 5;
    pub const VM_TF: i32 = 6;
    pub const VM_CEQ: i32 = 7;
    pub const VM_CDEQ: i32 = 8;
    pub const VM_CLT: i32 = 9;
    pub const VM_CGT: i32 = 10;
    pub const VM_SETF: i32 = 11;
    pub const VM_SETNF: i32 = 12;
    pub const VM_LNOT: i32 = 13;
    pub const VM_NF: i32 = 14;
    pub const VM_JF: i32 = 15;
    pub const VM_JNF: i32 = 16;
    pub const VM_JMP: i32 = 17;
    pub const VM_INC: i32 = 18;
    pub const VM_INCPD: i32 = 19;
    pub const VM_INCPI: i32 = 20;
    pub const VM_INCP: i32 = 21;
    pub const VM_DEC: i32 = 22;
    pub const VM_DECPD: i32 = 23;
    pub const VM_DECPI: i32 = 24;
    pub const VM_DECP: i32 = 25;
    pub const VM_LOR: i32 = 26;
    pub const VM_LORPD: i32 = 27;
    pub const VM_LORPI: i32 = 28;
    pub const VM_LORP: i32 = 29;
    pub const VM_LAND: i32 = 30;
    pub const VM_LANDPD: i32 = 31;
    pub const VM_LANDPI: i32 = 32;
    pub const VM_LANDP: i32 = 33;
    pub const VM_BOR: i32 = 34;
    pub const VM_BORPD: i32 = 35;
    pub const VM_BORPI: i32 = 36;
    pub const VM_BORP: i32 = 37;
    pub const VM_BXOR: i32 = 38;
    pub const VM_BXORPD: i32 = 39;
    pub const VM_BXORPI: i32 = 40;
    pub const VM_BXORP: i32 = 41;
    pub const VM_BAND: i32 = 42;
    pub const VM_BANDPD: i32 = 43;
    pub const VM_BANDPI: i32 = 44;
    pub const VM_BANDP: i32 = 45;
    pub const VM_SAR: i32 = 46;
    pub const VM_SARPD: i32 = 47;
    pub const VM_SARPI: i32 = 48;
    pub const VM_SARP: i32 = 49;
    pub const VM_SAL: i32 = 50;
    pub const VM_SALPD: i32 = 51;
    pub const VM_SALPI: i32 = 52;
    pub const VM_SALP: i32 = 53;
    pub const VM_SR: i32 = 54;
    pub const VM_SRPD: i32 = 55;
    pub const VM_SRPI: i32 = 56;
    pub const VM_SRP: i32 = 57;
    pub const VM_ADD: i32 = 58;
    pub const VM_ADDPD: i32 = 59;
    pub const VM_ADDPI: i32 = 60;
    pub const VM_ADDP: i32 = 61;
    pub const VM_SUB: i32 = 62;
    pub const VM_SUBPD: i32 = 63;
    pub const VM_SUBPI: i32 = 64;
    pub const VM_SUBP: i32 = 65;
    pub const VM_MOD: i32 = 66;
    pub const VM_MODPD: i32 = 67;
    pub const VM_MODPI: i32 = 68;
    pub const VM_MODP: i32 = 69;
    pub const VM_DIV: i32 = 70;
    pub const VM_DIVPD: i32 = 71;
    pub const VM_DIVPI: i32 = 72;
    pub const VM_DIVP: i32 = 73;
    pub const VM_IDIV: i32 = 74;
    pub const VM_IDIVPD: i32 = 75;
    pub const VM_IDIVPI: i32 = 76;
    pub const VM_IDIVP: i32 = 77;
    pub const VM_MUL: i32 = 78;
    pub const VM_MULPD: i32 = 79;
    pub const VM_MULPI: i32 = 80;
    pub const VM_MULP: i32 = 81;
    pub const VM_BNOT: i32 = 82;
    pub const VM_TYPEOF: i32 = 83;
    pub const VM_TYPEOFD: i32 = 84;
    pub const VM_TYPEOFI: i32 = 85;
    pub const VM_EVAL: i32 = 86;
    pub const VM_EEXP: i32 = 87;
    pub const VM_CHKINS: i32 = 88;
    pub const VM_ASC: i32 = 89;
    pub const VM_CHR: i32 = 90;
    pub const VM_NUM: i32 = 91;
    pub const VM_CHS: i32 = 92;
    pub const VM_INV: i32 = 93;
    pub const VM_CHKINV: i32 = 94;
    pub const VM_INT: i32 = 95;
    pub const VM_REAL: i32 = 96;
    pub const VM_STR: i32 = 97;
    pub const VM_OCTET: i32 = 98;
    pub const VM_CALL: i32 = 99;
    pub const VM_CALLD: i32 = 100;
    pub const VM_CALLI: i32 = 101;
    pub const VM_NEW: i32 = 102;
    pub const VM_GPD: i32 = 103;
    pub const VM_SPD: i32 = 104;
    pub const VM_SPDE: i32 = 105;
    pub const VM_SPDEH: i32 = 106;
    pub const VM_GPI: i32 = 107;
    pub const VM_SPI: i32 = 108;
    pub const VM_SPIE: i32 = 109;
    pub const VM_GPDS: i32 = 110;
    pub const VM_SPDS: i32 = 111;
    pub const VM_GPIS: i32 = 112;
    pub const VM_SPIS: i32 = 113;
    pub const VM_SETP: i32 = 114;
    pub const VM_GETP: i32 = 115;
    pub const VM_DELD: i32 = 116;
    pub const VM_DELI: i32 = 117;
    pub const VM_SRV: i32 = 118;
    pub const VM_RET: i32 = 119;
    pub const VM_ENTRY: i32 = 120;
    pub const VM_EXTRY: i32 = 121;
    pub const VM_THROW: i32 = 122;
    pub const VM_CHGTHIS: i32 = 123;
    pub const VM_GLOBAL: i32 = 124;
    pub const VM_ADDCI: i32 = 125;
    pub const VM_REGMEMBER: i32 = 126;
    pub const VM_DEBUGGER: i32 = 127;
    pub fn name(op: i32) -> &'static str {
        match op {
            0 => "VM_NOP",
            1 => "VM_CONST",
            2 => "VM_CP",
            3 => "VM_CL",
            4 => "VM_CCL",
            5 => "VM_TT",
            6 => "VM_TF",
            7 => "VM_CEQ",
            8 => "VM_CDEQ",
            9 => "VM_CLT",
            10 => "VM_CGT",
            11 => "VM_SETF",
            12 => "VM_SETNF",
            13 => "VM_LNOT",
            14 => "VM_NF",
            15 => "VM_JF",
            16 => "VM_JNF",
            17 => "VM_JMP",
            18 => "VM_INC",
            19 => "VM_INCPD",
            20 => "VM_INCPI",
            21 => "VM_INCP",
            22 => "VM_DEC",
            23 => "VM_DECPD",
            24 => "VM_DECPI",
            25 => "VM_DECP",
            26 => "VM_LOR",
            27 => "VM_LORPD",
            28 => "VM_LORPI",
            29 => "VM_LORP",
            30 => "VM_LAND",
            31 => "VM_LANDPD",
            32 => "VM_LANDPI",
            33 => "VM_LANDP",
            34 => "VM_BOR",
            35 => "VM_BORPD",
            36 => "VM_BORPI",
            37 => "VM_BORP",
            38 => "VM_BXOR",
            39 => "VM_BXORPD",
            40 => "VM_BXORPI",
            41 => "VM_BXORP",
            42 => "VM_BAND",
            43 => "VM_BANDPD",
            44 => "VM_BANDPI",
            45 => "VM_BANDP",
            46 => "VM_SAR",
            47 => "VM_SARPD",
            48 => "VM_SARPI",
            49 => "VM_SARP",
            50 => "VM_SAL",
            51 => "VM_SALPD",
            52 => "VM_SALPI",
            53 => "VM_SALP",
            54 => "VM_SR",
            55 => "VM_SRPD",
            56 => "VM_SRPI",
            57 => "VM_SRP",
            58 => "VM_ADD",
            59 => "VM_ADDPD",
            60 => "VM_ADDPI",
            61 => "VM_ADDP",
            62 => "VM_SUB",
            63 => "VM_SUBPD",
            64 => "VM_SUBPI",
            65 => "VM_SUBP",
            66 => "VM_MOD",
            67 => "VM_MODPD",
            68 => "VM_MODPI",
            69 => "VM_MODP",
            70 => "VM_DIV",
            71 => "VM_DIVPD",
            72 => "VM_DIVPI",
            73 => "VM_DIVP",
            74 => "VM_IDIV",
            75 => "VM_IDIVPD",
            76 => "VM_IDIVPI",
            77 => "VM_IDIVP",
            78 => "VM_MUL",
            79 => "VM_MULPD",
            80 => "VM_MULPI",
            81 => "VM_MULP",
            82 => "VM_BNOT",
            83 => "VM_TYPEOF",
            84 => "VM_TYPEOFD",
            85 => "VM_TYPEOFI",
            86 => "VM_EVAL",
            87 => "VM_EEXP",
            88 => "VM_CHKINS",
            89 => "VM_ASC",
            90 => "VM_CHR",
            91 => "VM_NUM",
            92 => "VM_CHS",
            93 => "VM_INV",
            94 => "VM_CHKINV",
            95 => "VM_INT",
            96 => "VM_REAL",
            97 => "VM_STR",
            98 => "VM_OCTET",
            99 => "VM_CALL",
            100 => "VM_CALLD",
            101 => "VM_CALLI",
            102 => "VM_NEW",
            103 => "VM_GPD",
            104 => "VM_SPD",
            105 => "VM_SPDE",
            106 => "VM_SPDEH",
            107 => "VM_GPI",
            108 => "VM_SPI",
            109 => "VM_SPIE",
            110 => "VM_GPDS",
            111 => "VM_SPDS",
            112 => "VM_GPIS",
            113 => "VM_SPIS",
            114 => "VM_SETP",
            115 => "VM_GETP",
            116 => "VM_DELD",
            117 => "VM_DELI",
            118 => "VM_SRV",
            119 => "VM_RET",
            120 => "VM_ENTRY",
            121 => "VM_EXTRY",
            122 => "VM_THROW",
            123 => "VM_CHGTHIS",
            124 => "VM_GLOBAL",
            125 => "VM_ADDCI",
            126 => "VM_REGMEMBER",
            127 => "VM_DEBUGGER",
            _ => "<UNKNOWN>",
        }
    }
}
